In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_excel("latest.xlsx")

In [3]:
df.head()

High__abs_energy  High__absolute_sum_of_changes  \
0      1.975064e+09                        6549.12   
1      1.094491e+09                        6401.74   
2      7.452665e+09                       10079.03   
3      9.731286e+10                       54768.88   
4      1.617532e+10                       12561.72   

   High__agg_autocorrelation__f_agg_"mean"__maxlag_40  \
0                                           0.978032    
1                                           0.977813    
2                                           0.011889    
3                                           0.760298    
4                                           0.777630    

   High__agg_autocorrelation__f_agg_"median"__maxlag_40  \
0                                           0.978772      
1                                           0.978643      
2                                           0.007736      
3                                           0.752790      
4                                           0.777902      

   High__agg_autocorrelation__f_agg_"var"__maxlag_40  \
0                                           0.000176   
1                                           0.000180   
2                                           0.000767   
3                                           0.016021   
4                                           0.000968   

   High__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"  \
0                                        -308.200242                     
1                                        -220.713699                     
2                                        2743.112499                     
3                                       14378.940923                     
4                                        4074.369594                     

   High__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"  \
0                                        -322.104256                      
1                                        -231.722674                      
2                                        2730.069070                      
3                                       13566.577716                      
4                                        4057.496626                      

   High__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"  \
0                                        -335.119071                     
1                                        -241.575131                     
2                                        2716.945297                     
3                                       12785.301960                     
4                                        4039.931091                     

   High__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"var"  \
0                                          90.549462                     
1                                          53.074467                     
2                                          68.797627                     
3                                      545511.901531                     
4                                         105.726122                     

   High__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"max"  ...  \
0                                        -201.750000                    ...   
1                                        -140.857571                    ...   
2                                        2748.965857                    ...   
3                                       17742.654143                    ...   
4                                        4080.022714                    ...   

   High__time_reversal_asymmetry_statistic__lag_1  \
0                                    1.650319e+07   
1                                    6.568537e+06   
2                                    2.216231e+05   
3                                   -1.706120e+11   
4                                   -6.576646e+06   

   High__time_reversal_asymmetry_statistic__lag_2  \
0         

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = df.drop('Target',1)
y = df.Target

In [6]:
X

High__abs_energy  High__absolute_sum_of_changes  \
0       1.975064e+09                        6549.12   
1       1.094491e+09                        6401.74   
2       7.452665e+09                       10079.03   
3       9.731286e+10                       54768.88   
4       1.617532e+10                       12561.72   
5       6.628756e+09                       14816.58   
6       1.590652e+10                       12685.86   
7       6.871833e+09                       15126.71   
8       1.994903e+10                       13674.97   
9       2.520860e+10                       30031.53   
10      2.542866e+10                       13635.82   
11      2.048714e+10                       26277.86   
12      1.319425e+10                       12017.89   
13      3.628114e+09                       13495.37   
14      9.742748e+09                       11434.17   
15      2.968888e+09                       12238.42   
16      4.274682e+09                        7592.31   
17      3.287695e+09                        8050.64   
18      9.378536e+09                       10509.80   
19      5.244712e+07                        6876.85   
20      1.150257e+10                       10241.26   
21      8.378930e+07                        6635.16   
22      7.822961e+09                        9593.51   
23      7.175686e+08                        7233.02   
24      1.198906e+10                       10141.09   
25      1.767120e+09                        7804.85   
26      8.210333e+09                        9185.72   
27      6.915017e+07                        6877.30   
28      1.118595e+10                       10376.61   
29      1.046335e+08                        7298.11   
30      1.182247e+10                       11361.60   
31      1.090708e+11                       59240.50   

    High__agg_autocorrelation__f_agg_"mean"__maxlag_40  \
0                                            0.978032    
1                                            0.977813    
2                                            0.011889    
3                                            0.760298    
4                                            0.777630    
5                                            0.846654    
6                                            0.786434    
7                                            0.849251    
8                                            0.873379    
9                                            0.780332    
10                                           0.852541    
11                                           0.787363    
12                                           0.773013    
13                                           0.834649    
14                                           0.648623    
15                                           0.834976    
16                                           0.002073    
17                                           0.985672    
18                                           0.976681    
19                                           0.965637    
20                                           0.976808    
21                                           0.966747    
22                                           0.983927    
23                                           0.976175    
24                                           0.982816    
25                                           0.978365    
26                                           0.979781    
27                                           0.961210    
28                                           0.980917    
29                                           0.961153    
30                                           0.009260    
31                                           0.744848    

    High__agg_autocorrelation__f_agg_"median"__maxlag_40  \
0                                            0.978772      
1                                            0.978643      
2                                            0.007736      
3                                

In [7]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    1
29    0
30    1
31    0
Name: Target, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# pytcart tune Random forest model

In [10]:
classifier = RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=60, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=5635,
                       verbose=0, warm_start=False)

In [11]:
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=60, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=5635,
                       verbose=0, warm_start=False)

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
print(accuracy_score(y_test,y_pred))

0.9


In [14]:
print(confusion_matrix(y_test,y_pred))

[[5 1]
 [0 4]]


In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.80      1.00      0.89         4

    accuracy                           0.90        10
   macro avg       0.90      0.92      0.90        10
weighted avg       0.92      0.90      0.90        10



# pytcart tune Decison tree model

In [16]:
from sklearn import tree
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
classifier  = tree.DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=150, max_features=251, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=6624, splitter='best')

In [18]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=150, max_features=251, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=6624, splitter='best')

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
print(accuracy_score(y_test,y_pred))

0.8


In [21]:
print(confusion_matrix(y_test,y_pred))

[[5 1]
 [1 3]]


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83         6
           1       0.75      0.75      0.75         4

    accuracy                           0.80        10
   macro avg       0.79      0.79      0.79        10
weighted avg       0.80      0.80      0.80        10



# Sklearn Random forest model

In [23]:
classifier = RandomForestClassifier()

In [24]:
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
print(accuracy_score(y_test,y_pred))

0.9


In [27]:
print(confusion_matrix(y_test,y_pred))

[[5 1]
 [0 4]]


In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.80      1.00      0.89         4

    accuracy                           0.90        10
   macro avg       0.90      0.92      0.90        10
weighted avg       0.92      0.90      0.90        10

